### ISSUE TITLE
Enos deploy on Grid'5000 fails

### ISSUE THREAD

**Issue by mabderrahim** [BeyondTheClouds/enos#131] opened 2017-05-03 08:50 UTC
`python -m enos.enos deploy` on a fronted node of Grid'5000 fails with this error message :

```
 Warning: Permanently added 'grenoble.grid5000.fr,172.16.31.101' (ECDSA) to the list of known hosts.
Permission denied (publickey,password).
INFO:root:Criteria for the reservation: [   (   OarSubmission(resources="{cluster='paravance'}/nodes=3+{type='kavlan'}/vlan=1", name='Enos'),
        u'rennes')]
INFO:root:Using new oargrid job 58431
INFO:root:Using vlan ('rennes', 4)
INFO:root:Deploying jessie-x64-min on 3 nodes (forced)
INFO:root:[Host('paravance-72-kavlan-4.rennes.grid5000.fr'), Host('paravance-8-kavlan-4.rennes.grid5000.fr'), Host('paravance-9-kavlan-4.rennes.grid5000.fr')]
INFO:root:{'paravance': [Host(paravance-72-kavlan-4.rennes.grid5000.fr, address=paravance-72-kavlan-4.rennes.grid5000.fr), Host(paravance-8-kavlan-4.rennes.grid5000.fr, address=paravance-8-kavlan-4.rennes.grid5000.fr), Host(paravance-9-kavlan-4.rennes.grid5000.fr, address=paravance-9-kavlan-4.rennes.grid5000.fr)], 'control': [Host(paravance-72-kavlan-4.rennes.grid5000.fr, address=paravance-72-kavlan-4.rennes.grid5000.fr)], 'compute': [Host(paravance-9-kavlan-4.rennes.grid5000.fr, address=paravance-9-kavlan-4.rennes.grid5000.fr)], 'network': [Host(paravance-8-kavlan-4.rennes.grid5000.fr, address=paravance-8-kavlan-4.rennes.grid5000.fr)]}
INFO:root:Using vlan ('rennes', 4)
INFO:root:cidr : 10.24.0.0/18
INFO:root:Using vlan ('rennes', 4)
2017-05-03 09:55:39,505 INFO: Setting ['paravance-8-eth1.rennes.grid5000.fr', 'paravance-72-eth1.rennes.grid5000.fr', 'paravance-9-eth1.rennes.grid5000.fr'] in vlan 4 of site rennes
INFO:execo:Setting ['paravance-8-eth1.rennes.grid5000.fr', 'paravance-72-eth1.rennes.grid5000.fr', 'paravance-9-eth1.rennes.grid5000.fr'] in vlan 4 of site rennes
INFO:root:mounting secondary interface
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mabderrahim/enos/enos/enos.py", line 659, in <module>
    main()
  File "/home/mabderrahim/enos/enos/enos.py", line 635, in main
    deploy(**docopt(deploy.__doc__, argv=argv))
  File "enos/utils/enostask.py", line 78, in decorated
    fn(*args, **kwargs)
  File "/home/mabderrahim/enos/enos/enos.py", line 604, in deploy
    up(**kwargs)
  File "enos/utils/enostask.py", line 78, in decorated
    fn(*args, **kwargs)
  File "/home/mabderrahim/enos/enos/enos.py", line 126, in up
    provider.init(env['config'], CALL_PATH, kwargs['--force-deploy'])
  File "enos/provider/g5k.py", line 65, in init
    vlans)
  File "enos/provider/g5k.py", line 383, in _mount_cluster_nics
    'mounting secondary interface')
  File "enos/provider/g5k.py", line 406, in _exec_command_on_nodes
    remote = EX.Remote(cmd, nodes, conn_params)
  File "/home/mabderrahim/enos/venv/local/lib/python2.7/site-packages/execo/action.py", line 520, in __init__
    self._init_processes()
  File "/home/mabderrahim/enos/venv/local/lib/python2.7/site-packages/execo/action.py", line 550, in _init_processes
    p = SshProcess(remote_substitute(self.cmd, self.hosts, index, self._caller_context),
  File "/home/mabderrahim/enos/venv/local/lib/python2.7/site-packages/execo/substitutions.py", line 69, in remote_substitute
    string = re.sub("\{\{\{host\}\}\}", all_hosts[index].address, string)
  File "/home/mabderrahim/enos/venv/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/mabderrahim/enos/venv/lib/python2.7/re.py", line 286, in _subx
    template = _compile_repl(template, pattern)
  File "/home/mabderrahim/enos/venv/lib/python2.7/re.py", line 266, in _compile_repl
    p = _cache_repl.get(key)
TypeError: unhashable type: 'set'
```

**Comment by msimonin** [comment] 2017-05-03 08:52
Hello @mabderrahim,

The error seems related to the second network interface.
Could you try with the following : 
```
provider:
  single_interface: true
```
This could be probably be used as a temporary workaround until we dig this issue.

**Comment by jirerw** [comment] 2017-05-03 11:54
Thanks @msimonin 

Adding
`provider:
  single_interface: true`
solved the problem.

However, this task of ansible fails :
`TASK [registry : Waiting for the registry service to become available] *********
fatal: [paravance-72-kavlan-4.rennes.grid5000.fr]: FAILED! => {"changed": false, "elapsed": 120, "failed": true, "msg": "Timeout when waiting for 10.24.61.254:4000"}`
and this warning appears 
`[WARNING]: Cannot write to InfluxDB, check the service state on 10.24.61.253`

**Comment by mabderrahim** [comment] 2017-05-03 11:55
Thanks @msimonin

Adding
`provider:
  single_interface: true`
solved the problem.

However, this task of ansible fails :
`TASK [registry : Waiting for the registry service to become available] *********
fatal: [paravance-72-kavlan-4.rennes.grid5000.fr]: FAILED! => {"changed": false, "elapsed": 120, "failed": true, "msg": "Timeout when waiting for 10.24.61.254:4000"}`
and this warning appears 
`[WARNING]: Cannot write to InfluxDB, check the service state on 10.24.61.253`

**Comment by msimonin** [comment] 2017-05-03 12:00
If you are using the sample configuration file. The registry will use a shared rbd as backend. This one is maybe corrupted. 
I suggest you to have your own one : 
https://enos.readthedocs.io/en/latest/customization/index.html#using-a-persistent-registry-with-ceph

**Comment by msimonin** [comment] 2017-05-04 14:25
As a follow up there are two distincts errors here : 
1) Mounting the secondary interfaces is failing
2) The registry doesn't start

For 1) I'll provide a fix in a few
For 2) I can't reproduce and it's most probably an environmental issue. Please check with your own registry backend (link in the previous post)

```
TASK [registry : Add a vip address for influx db] ******************************
changed: [paravance-38-kavlan-4.rennes.grid5000.fr]

TASK [registry : Starting the Docker registry] *********************************
changed: [paravance-38-kavlan-4.rennes.grid5000.fr]

TASK [registry : Waiting for the registry service to become available] *********
ok: [paravance-38-kavlan-4.rennes.grid5000.fr]
```

**Comment by msimonin** [comment] 2017-05-05 08:32
@mabderrahim 
A fixed has been merged for 1)
For 2) I've rebuild the rbd. But I suggest you to manage your own registry backend (see the link above).

**Closed** 2017-05-11 09:38 UTC
Labels: bug, provider-g5k
