### ISSUE TITLE
g5k provision - unable to access to vm created

### ISSUE THREAD

**Issue by manuvaldi** [BeyondTheClouds/enos#150] opened 2017-06-08 10:43 UTC
When I run deploy over g5k with default reservation. After provision VM on Openstack I can't reach instances.

Seems to be router can't reach external network.

```
root@parapluie-2-kavlan-4:~# ping -c 5 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=55 time=25.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=55 time=25.1 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=55 time=25.1 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=55 time=25.1 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=55 time=25.0 ms

--- 8.8.8.8 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4005ms
rtt min/avg/max/mdev = 25.079/25.168/25.286/0.121 ms
root@parapluie-2-kavlan-4:~# ip netns exec qrouter-7a7d81e8-f9f3-4504-ae15-a8347de918f1 ping -c5 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
From 10.24.26.1 icmp_seq=1 Destination Host Unreachable
From 10.24.26.1 icmp_seq=2 Destination Host Unreachable
From 10.24.26.1 icmp_seq=3 Destination Host Unreachable
From 10.24.26.1 icmp_seq=4 Destination Host Unreachable
From 10.24.26.1 icmp_seq=5 Destination Host Unreachable

--- 8.8.8.8 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4024ms
```

**Comment by msimonin** [comment] 2017-06-09 09:10
Hello @manuvaldi,

`parapluie-2` has only one network interface, in this case you are right the external network won't be reachable. Alternatively if you deploy on a cluster whose machines have at least 2 nics this should be ok ( To be honnest we don't put so much effort to configure correctly the network when only one nic is available : I've opened #151 to track the progress on this).

e.g with `paravance` cluster : 

```
root@paravance-71-kavlan-4:~# ip netns exec qrouter-2060e16c-3e3a-4db2-aca0-cbb627792056 ping -c 5 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=55 time=26.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=55 time=25.0 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=55 time=25.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=55 time=26.0 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=55 time=38.5 ms
```

**Comment by manuvaldi** [comment] 2017-06-09 09:49
The same problem with other sites and cluster with more than 1 interface. By the moment I use only paravance cluster.

**Comment by msimonin** [comment] 2017-06-09 09:54
Could you provide the steps to reproduce what you are experiencing, including the `reservation.yml` used ?

**Comment by manuvaldi** [comment] 2017-06-09 10:47
```
---
# ############################################### #
# Enos Configuration File                         #
# ############################################### #

# Provider specific config
provider:
  type: g5k
  name: 'Enos'
  walltime: "2:00:00"


  # mandatory : you need to have exacly one vlan
  vlans:
     rennes: "{type='kavlan'}/vlan=1"
  # Be less strict on node distribution especially
  # when nodes are missing in the reservation
  # or not deployed
  role_distribution: debug

# Resources description
resources:
  parapluie:
    control: 1
    compute: 2
    network: 1

# ############################################### #
# Inventory to use                                #
# ############################################### #

# This will describe the topology of your services
inventory: inventories/inventory.sample

# ############################################### #
# docker registry parameters
# ############################################### #
registry:
  ceph: false
  ceph_keyring: /home/mvalle/.ceph/ceph.client.mvalle.keyring
  ceph_id: mvalle
  ceph_rbd: mvalle_kolla_registry/datas
  ceph_mon_host:
    - ceph0.rennes.grid5000.fr
    - ceph1.rennes.grid5000.fr
    - ceph2.rennes.grid5000.fr

# ############################################### #
# Kolla parameteres                               #
# ############################################### #
# Repository
kolla_repo: "https://git.openstack.org/openstack/kolla-ansible"
kolla_ref: "stable/ocata"


# globals.yml
kolla:
  kolla_base_distro: "centos"
  kolla_install_type: "source"
  docker_namespace: "beyondtheclouds"
  enable_heat: "no"
```

**Comment by msimonin** [comment] 2017-06-09 12:06
Until #151 is resolved, you should try `paravance`
, `paranoia`, `parasilo` or whatever cluster that have 2 nics. You can refer to the hardware section of the Grid'5000 documentation to check the nodes capabilities.

**Comment by rcherrueau** [comment] 2017-06-09 12:30
According to @msimonin  you should change the cluster name under `resources` key of your `reservation.yaml`. For instance, going with `paravance` looks like:

```yaml
# Resources description
resources:
  paravance: # Note the `paravance` here
    control: 1
    compute: 2
    network: 1
```

You should also be sure that you don't have an already existing reservation with the name `Enos`. In that case, Enos don't look at the `resources` key, and directly reuse information provided by `oargidstat`. 

One common mistake is doing an `enos deploy` with resources on, lets say, `clusterA`, then change `reservation.yaml` with resources on `clusterB` and redo an `enos deploy`. If you do so, enos will continue to deploy on `clusterA`. 

To prevent such a case, you have two possibilities. First, free your reservation with `enos destroy --hard` (or using g5k `oargridstat`, `oargriddel`). Second possibility is to change the name of your reservation in the `reservation.yaml`:

```
provider:
  type: g5k
  name: 'EnosOnParavance'
```

Do not hesitate to join the [gitter/enos](https://gitter.im/BeyondTheClouds/enos?source=orgpage) if you need help.

**Comment by msimonin** [comment] 2017-07-04 14:12
Any progress here ?

**Comment by msimonin** [comment] 2017-08-07 07:48
@manuvaldi I'm closing this issue. Let us know if you need further help by reopening it.

**Closed by msimonin** 2017-08-07 07:48 UTC
Labels: g5k

**Comment by cmcornejocrespo** [comment] 2017-08-08 07:34
Hi @manuvaldi,

Running our tests in a cluster with at least two nics, seems to be working fine. Shall we close this one?
